Allow to use urls too instead of only usernames

diff --git a/github-clone-public-repos b/github-clone-public-repos
--- a/github-clone-public-repos
+++ b/github-clone-public-repos
@@ -1,23 +1,55 @@
 #!/bin/bash
 
-# Check if the username parameter is provided
-if [ $# -eq 0 ]; then
-    echo "Error: GitHub username is missing."
-    echo "Usage: $0 <username> [target_directory]"
+# Check if jq is installed
+if ! command -v jq >/dev/null; then
+    echo "Error: 'jq' is not installed. Please install 'jq' before running this script."
     exit 1
 fi
 
-# Set the GitHub username
-USERNAME="$1"
+# Check if the username/URL parameter is provided
+if [ $# -eq 0 ]; then
+    echo "Error: GitHub username or URL is missing."
+    echo "Usage: $0 <username_or_url> [target_directory]"
+    exit 1
+fi
+
+# Function to extract the GitHub username from a URL
+extract_username_from_url() {
+    local url=$1
+    local username=""
+    if [[ $url =~ github\.com/([^/]+) ]]; then
+        username=${BASH_REMATCH[1]}
+    fi
+    echo "$username"
+}
+
+# Function to extract the repository name from a URL
+extract_repo_name_from_url() {
+    local url=$1
+    local repo_name=""
+    if [[ $url =~ github\.com/[^/]+/([^/]+)/?.* ]]; then
+        repo_name=${BASH_REMATCH[1]}
+    fi
+    echo "$repo_name"
+}
+
+# Extract the GitHub username or URL from the parameter
+PARAMETER="$1"
+USERNAME=$(extract_username_from_url "$PARAMETER")
 
 # Set the target directory or fallback to the current directory
 TARGET_DIR="${2:-$(pwd)}"
-mkdir $TARGET_DIR -p
+mkdir "$TARGET_DIR" -p
+
+if [ -z "$USERNAME" ]; then
+  # The input is a username
+  USERNAME="$PARAMETER"
+fi
 
 # Fetch the repository URLs using the GitHub API
-REPO_URLS=$(curl -s "https://api.github.com/users/$USERNAME/repos?type=public&per_page=1000" | grep -o 'git@[^"]*')
+REPO_URLS=$(curl -s "https://api.github.com/users/$USERNAME/repos?type=public&per_page=1000" | jq -r '.[].clone_url')
 
-# Check if the username is valid and repositories are found
+# Check if repositories are found
 if [ -z "$REPO_URLS" ]; then
     echo "No public repositories found for the GitHub user: $USERNAME"
     exit 1
@@ -28,7 +60,7 @@ for URL in $REPO_URLS; do
     # Extract the repository name from the URL
     REPO_NAME=$(basename -s .git "$URL")
     echo
-    echo "Processing $REPO_NAME"
+    echo "Processing '$REPO_NAME'..."
     echo "============================================"
 
     # Check if the directory already exists
diff --git a/gitlab-clone-public-repos b/gitlab-clone-public-repos
--- a/gitlab-clone-public-repos
+++ b/gitlab-clone-public-repos
@@ -1,27 +1,84 @@
 #!/bin/bash
 
-# Check if the instance URL and username parameters are provided
-if [ $# -lt 2 ]; then
-    echo "Error: GitLab instance URL or username is missing."
-    echo "Usage: $0 <instance_url> <username> [target_directory]"
+# Check if jq is installed
+if ! command -v jq >/dev/null; then
+    echo "Error: 'jq' is not installed. Please install 'jq' before running this script."
     exit 1
 fi
 
-# Set the GitLab instance URL and username
-INSTANCE_URL="$1"
-USERNAME="$2"
+# Check if awk is installed
+if ! command -v awk >/dev/null; then
+    echo "Error: 'awk' is not installed. Please install 'awk' before running this script."
+    exit 1
+fi
+
+# Check if sed is installed
+if ! command -v sed >/dev/null; then
+    echo "Error: 'sed' is not installed. Please install 'sed' before running this script."
+    exit 1
+fi
+
+# Check if the GitLab URL parameter is provided
+if [ $# -lt 1 ]; then
+    echo "Error: GitLab URL is missing."
+    echo "Usage: $0 <gitlab_url> [target_directory]"
+    exit 1
+fi
+
+# Function to extract the GitLab username from the URL
+extract_gitlab_username() {
+    local url=$1
+    local username=""
+
+    # Extract the username from the URL
+    if [[ $url == *"://"* ]]; then
+        username=$(echo "$url" | awk -F/ '{print $4}')
+    elif [[ $url == *"/"* ]]; then
+        username=$(echo "$url" | awk -F/ '{print $2}')
+    else
+        username="$url"
+    fi
+
+    echo "$username"
+}
+
+# Function to extract the GitLab hostname from the URL
+extract_gitlab_hostname() {
+    local url=$1
+    local hostname=""
+
+    # Extract the hostname from the URL
+    if [[ $url =~ ^(?:https?://)?([^/]+) ]]; then
+        hostname=${BASH_REMATCH[1]}
+    fi
+
+    # Use "gitlab.com" as the default if hostname is empty
+    if [ -z "$hostname" ]; then
+        hostname="gitlab.com"
+    fi
+
+    echo "$hostname"
+}
+
+
+# Extract the GitLab username and hostname from the GitLab URL
+GITLAB_URL="$1"
+GITLAB_URL=${GITLAB_URL%/}  # Remove trailing slash if present
+USERNAME=$(extract_gitlab_username "$GITLAB_URL")
+HOSTNAME=$(extract_gitlab_hostname "$GITLAB_URL")
+
 
 # Add "https://" if the URL doesn't start with it
-if ! [[ $INSTANCE_URL =~ ^https?:// ]]; then
-    INSTANCE_URL="https://$INSTANCE_URL"
+if ! [[ $HOSTNAME =~ ^https?:// ]]; then
+    HOSTNAME="https://$HOSTNAME"
 fi
 
 # Set the target directory or fallback to the current directory
-TARGET_DIR="${3:-$(pwd)}"
-mkdir $TARGET_DIR -p
+TARGET_DIR="${2:-$(pwd)}"
+mkdir "$TARGET_DIR" -p
 
 # Fetch the repository URLs using the GitLab API
-REPO_URLS=$(curl -s "$INSTANCE_URL/api/v4/users/$USERNAME/projects?visibility=public&per_page=1000" | jq -r '.[].http_url_to_repo')
+REPO_URLS=$(curl -s "$HOSTNAME/api/v4/users/$USERNAME/projects?visibility=public&per_page=1000" | jq -r '.[].http_url_to_repo')
 
 # Check if the username is valid and repositories are found
 if [ -z "$REPO_URLS" ]; then
@@ -34,7 +91,7 @@ for URL in $REPO_URLS; do
     # Extract the repository name from the URL
     REPO_NAME=$(basename -s .git "$URL")
     echo
-    echo "Processing $REPO_NAME"
+    echo "Processing '$REPO_NAME'..."
     echo "============================================"
 
     # Check if the directory already exists
